/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package login;

import java.awt.HeadlessException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author HP
 */
public class EntryPanel extends javax.swing.JPanel {

    /**
     * Creates new form EntryPanel
     * @throws java.sql.SQLException
     * @throws java.io.IOException
     */
    public static Db instance; 
    private final String DB_TYPE = "mysql"; 
    private final String DB_HOST = "localhost"; 
    private final String DB_PORT = "3306"; 
    private final String DB_NAME = "pbo"; 
    private final String DB_USER = "root"; 
    private final String DB_PASS = ""; 
    
    public EntryPanel() throws SQLException, IOException {
        initComponents();
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        mahasiswaTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lakiRadioButton = new javax.swing.JRadioButton();
        bernyanyiCheckBox = new javax.swing.JCheckBox();
        perempuanRadioButton = new javax.swing.JRadioButton();
        berenangCheckBox = new javax.swing.JCheckBox();
        umurSpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        provinsiComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nimTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        membacaCheckBox = new javax.swing.JCheckBox();
        updateButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        simpanButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(704, 900));
        setLayout(new java.awt.BorderLayout());

        mahasiswaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM ", "Nama", "Jenis Kelamin", "Umur", "Alamat", "Provinsi", "Hobi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        mahasiswaTable.setPreferredSize(new java.awt.Dimension(400, 500));
        mahasiswaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mahasiswaTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(mahasiswaTable);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));

        buttonGroup1.add(lakiRadioButton);
        lakiRadioButton.setText("Laki-laki");
        lakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiRadioButtonActionPerformed(evt);
            }
        });

        bernyanyiCheckBox.setText("Bernyanyi");

        buttonGroup1.add(perempuanRadioButton);
        perempuanRadioButton.setText("Perempuan");

        berenangCheckBox.setText("Berenang");

        umurSpinner.setModel(new javax.swing.SpinnerNumberModel(10, 1, 90, 1));

        jLabel6.setText("Provinsi");

        jLabel3.setText("Umur");

        jLabel7.setText("Hobi");

        jLabel4.setText("Jenis Kelamin");

        alamatTextArea.setColumns(20);
        alamatTextArea.setRows(5);
        jScrollPane1.setViewportView(alamatTextArea);

        provinsiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Aceh", "2. Bali", "3. Bangka Belitung", "4. Banten", "5. Bengkulu", "6. Jawa Tengah", "7. Kalimantan Tengah", "8. Sulawesi Tengah", "9. Jawa timur", "10. Kalimantan Timur", "11. Nusa Tenggara Timur", "12. Gorontalo", "13. Daerah Khusus Ibukota Jakarta", "14. Jambi", "15. Lampung", "16. Maluku", "17. Sulawesi Utara", "18. Sumatera Utara", "19. Papua", "20. Riau", "21. Kepulauan Riau", "22. Sulawesi Tenggara", "23. Kalimantan Selatan", "24. Sulawesi Selatan", "25. Sumatera Selatan", "26. Jawa Barat", "27. Kalimantan Barat", "28. Nusa tenggara Barat", "29. Papua Barat", "30. Sulawesi Barat", "31. Sumatera Barat", "32. Daerah Istimewa Yogyakarta", "33. Kalimantan Utara", "34. Maluku Utara", " " }));
        provinsiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinsiComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Alamat");

        jLabel1.setText("Nama");

        nimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("NIM");

        membacaCheckBox.setText("Membaca");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(hapusButton)
                        .addGap(18, 18, 18)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpanButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 134, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3))
                    .addGap(54, 54, 54)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lakiRadioButton)
                        .addComponent(perempuanRadioButton)
                        .addComponent(umurSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bernyanyiCheckBox)
                        .addComponent(berenangCheckBox)
                        .addComponent(membacaCheckBox)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(provinsiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(245, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(137, 137, 137)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(hapusButton)
                    .addComponent(simpanButton))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lakiRadioButton)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(perempuanRadioButton)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(umurSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGap(54, 54, 54)
                    .addComponent(jLabel5)
                    .addGap(86, 86, 86)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(provinsiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGap(48, 48, 48)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(membacaCheckBox)
                        .addComponent(jLabel7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(bernyanyiCheckBox)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(berenangCheckBox)
                    .addContainerGap(498, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void lakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiRadioButtonActionPerformed

    private void provinsiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinsiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinsiComboBoxActionPerformed

    private void nimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimTextFieldActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
        

        Mahasiswa mhs = new Mahasiswa();
        mhs.setNim(nimTextField.getText());
        mhs.setNama(namaTextField.getText());
        if(lakiRadioButton.isSelected()){
            mhs.setJenisKelamin("Laki-laki");
        }

        if(perempuanRadioButton.isSelected()){
            mhs.setJenisKelamin("Perempuan");
        }

        int umur = (Integer) umurSpinner.getValue();
        mhs.setUmur(umur);
        mhs.setAlamat(alamatTextArea.getText());

        mhs.setProvinsi(provinsiComboBox.getSelectedItem().toString());
        ArrayList<String> hobiList = new ArrayList<>();
        if (membacaCheckBox.isSelected()){
            hobiList.add("Membaca");
        }

        if(bernyanyiCheckBox.isSelected()){
            hobiList.add("menyanyi");
        }
        if(berenangCheckBox.isSelected()){
            hobiList.add("berenang");
        }
        mhs.setHobi(hobiList);
        try {
            Db.getInstance().insertMahasiswa(mhs);
            clearForm();
            JOptionPane.showMessageDialog(this, "Sukses Tersimpan");
            loadTableData();
        } catch (SQLException | IOException ex) {
            Logger.getLogger(EntryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        //DefaultTableModel dtm = (DefaultTableModel) mahasiswaTable.getModel();
        //dtm.addRow(new Object[] {mhs.getNim(),mhs.getNama(),mhs.getJenisKelamin(),mhs.getUmur()});
       
        
        
        
        //DefaultTableModel dtm = (DefaultTableModel) mahasiswaTable.getModel();
        //dtm.addRow(new Object[] {mhs.getNim(),mhs.getNama(),mhs.getJenisKelamin(),mhs.getUmur()});
        
     

        

    }//GEN-LAST:event_simpanButtonActionPerformed

    private void mahasiswaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mahasiswaTableMouseClicked
        // TODO add your handling code here:
        simpanButton.setEnabled(false);
         int i = mahasiswaTable.getSelectedRow();
         if (i ==-1){
             return;
         }
        
        
        nimTextField.setText(mahasiswaTable.getValueAt(i,0).toString());
        namaTextField.setText(mahasiswaTable.getValueAt(i,1).toString());
        //buttonGroup1.setSelected(mahasiswaTable.getValueAt(lakiButton, row));
        umurSpinner.setValue(mahasiswaTable.getValueAt(i, 3));
        alamatTextArea.setText(mahasiswaTable.getValueAt(i, 4).toString());
        provinsiComboBox.setSelectedItem(mahasiswaTable.getValueAt(i, 5).toString());
       ArrayList<String> hobiList = new ArrayList<>();
       Mahasiswa mhs = new Mahasiswa();
        if (membacaCheckBox.isSelected()){
            hobiList.add("Membaca");
        }

        if(bernyanyiCheckBox.isSelected()){
            hobiList.add("menyanyi");
        }
        if(berenangCheckBox.isSelected()){
            hobiList.add("berenang");
        }
        mhs.setHobi(hobiList);
        ArrayList<String> hobi = mhs.getHobi();
        mahasiswaTable.setValueAt(hobi,i,6);
                
        
    }//GEN-LAST:event_mahasiswaTableMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        int i = mahasiswaTable.getSelectedRow();
        if(i==-1){
            return;
        }
        String nim, nama, alamat, provinsi,jenisKelamin;
        int umur;
         ArrayList<String> hobiList = new ArrayList<>();
        Mahasiswa mhs = new Mahasiswa();
        
        nim = nimTextField.getText();
        nama = namaTextField.getText();
        alamat = alamatTextArea.getText();
        umur = (int) umurSpinner.getValue();
        provinsi = provinsiComboBox.getSelectedItem().toString();
        jenisKelamin = setJK(mhs);
        
         if (membacaCheckBox.isSelected()){
            hobiList.add("Membaca");
        }

        if(bernyanyiCheckBox.isSelected()){
            hobiList.add("menyanyi");
        }
        if(berenangCheckBox.isSelected()){
            hobiList.add("berenang");
        }
        mhs.setHobi(hobiList);
        ArrayList<String> hobi = mhs.getHobi();
        //mahasiswaTable.setValueAt(hobi,i,6);
        
        try{
    Connection conn = getConnection();
    String sql = "update mahasiswa set nim=?, nama=? , alamat=?,umur=?,provinsi=?,hobi=?,jenis_kelamin=? where nim =?";
      
    PreparedStatement stmt = conn.prepareStatement(sql);
      stmt = conn.prepareStatement(sql);
      stmt.setString(1,nim);
      stmt.setString(2,nama);
      stmt.setString(3,alamat);
      stmt.setInt(4,umur);
      stmt.setString(5, provinsi);
      //stmt.setString(6,hobi);
      stmt.setString(6,setList(hobi));
      stmt.setString(7,setJK(mhs));
      stmt.setString(8,nim);
      stmt.executeUpdate();
      //stmt.close();
      
      JOptionPane.showMessageDialog(null, "Updated!");
      loadTableData();
      clearForm();
}catch(HeadlessException | SQLException e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}       catch (IOException ex) {
            Logger.getLogger(EntryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:
        String nim;
        
        int i = mahasiswaTable.getSelectedRow();
        if(i==-1){
            return;
        }
        nim = (String) mahasiswaTable.getValueAt(i,0);
        
    try{
    Connection conn = getConnection();
    String sql = "delete from mahasiswa where nim=?";
    PreparedStatement stmt = conn.prepareStatement(sql);
    stmt = conn.prepareStatement(sql);
    stmt.setString(1, nim);
    stmt.executeUpdate();
    stmt.close();
    JOptionPane.showMessageDialog(null, "Deleted!");
    loadTableData();
    clearForm();
    }catch(SQLException ex){
     ex.getMessage();
     JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
    }   catch (IOException ex) {
            Logger.getLogger(EntryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_hapusButtonActionPerformed
private void loadTableData() throws SQLException, IOException{
       DefaultTableModel dtm = (DefaultTableModel) mahasiswaTable.getModel(); 
       //refresh tabel 
       while(dtm.getRowCount()>0){ 
           dtm.removeRow(0); 
       } 
       
        try{
       //isi tabel 
        for(Mahasiswa mhs: Db.getInstance().getListMahasiswa()){ 
            dtm.addRow(new Object[]{mhs.getNim(),mhs.getNama(),mhs.getJenisKelamin(),mhs.getUmur(),mhs.getAlamat(),mhs.getProvinsi(),mhs.getHobi()}); 
        } 
       } catch (SQLException ex){
               System.err.println(ex);
         JOptionPane.showMessageDialog(this, "Gagal mengambil data", "Gagal", 
                 JOptionPane.ERROR_MESSAGE);
       }
    }

private void clearForm(){
        
        nimTextField.setText("");
        namaTextField.setText(""); 
        buttonGroup1.clearSelection(); 
        umurSpinner.setValue(15); 
        alamatTextArea.setText(""); 
        provinsiComboBox.setSelectedIndex(-1); 
        membacaCheckBox.setSelected(false); 
        bernyanyiCheckBox.setSelected(false); 
        berenangCheckBox.setSelected(false);
    }

    /**
     *
     * @param hobi
     * @return
     */
    public String setList(ArrayList<String> hobi){
           
       
    
        return  hobi.toString();
    
    
}
    public String setJK(Mahasiswa mhs){
        
        if(lakiRadioButton.isSelected()){
            mhs.setJenisKelamin("Laki-laki");
        }

        if(perempuanRadioButton.isSelected()){
            mhs.setJenisKelamin("Perempuan");
        }
        
        return mhs.getJenisKelamin();
    }
    
    



private Connection getConnection() throws SQLException { 
      
      
      return DriverManager.getConnection("jdbc:"+DB_TYPE+"://"+DB_HOST+":"+DB_PORT+"/"+DB_NAME,DB_USER,DB_PASS); 
      
      
      //connect jika berhasil notif
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JCheckBox berenangCheckBox;
    private javax.swing.JCheckBox bernyanyiCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton lakiRadioButton;
    private javax.swing.JTable mahasiswaTable;
    private javax.swing.JCheckBox membacaCheckBox;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JComboBox<String> provinsiComboBox;
    private javax.swing.JButton simpanButton;
    private javax.swing.JSpinner umurSpinner;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
