/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package login;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author HP
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    private JScrollPane contentScrollPane;
    public static Db instance; 
    private final String DB_TYPE = "mysql"; 
    private final String DB_HOST = "localhost"; 
    private final String DB_PORT = "3306"; 
    private final String DB_NAME = "pbo"; 
    private final String DB_USER = "root"; 
    private final String DB_PASS = ""; 
    private JScrollPane JScrollPane;
    public LoginPanel() {
        initComponents();
    }
    
    public LoginPanel(JScrollPane contentScrollPane) {
        initComponents();
        this.contentScrollPane = contentScrollPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        unameTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        logBtn = new javax.swing.JButton();
        passwordTextField = new javax.swing.JPasswordField();

        jLabel7.setText("Username");

        jLabel8.setText("Password");

        logBtn.setText("Login");
        logBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(unameTextField)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logBtn)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(unameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(logBtn)
                .addContainerGap(285, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBtnActionPerformed
        // TODO add your handling code here:
        //contentScrollPane.setViewportView(new HomePanel());
       /* try{
       
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pbo?useSSL=false","root","");
            String username=jTextField1.getText();
            String password=jTextField2.getText();
            
            Statement stm=con.createStatement();
            String sql="select *from tabeluser where username='"+username+"'and password='"+password+"'";
               
        ResultSet rs=stm.executeQuery(sql);
 
        if(rs.next()){
        contentScrollPane.setViewportView(new HomePanel(aturmenu));


        }else{
            JOptionPane.showMessageDialog(this,"username or password wrong");
         jTextField1.setText("");
         jTextField2.setText("");
         
        }
        
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }*/
       
       try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
           try (Connection conn = DriverManager.getConnection("jdbc:"+DB_TYPE+"://"+DB_HOST+":"+DB_PORT+"/"+DB_NAME,DB_USER,DB_PASS)) {
               String username = unameTextField.getText();
               String password = passwordTextField.getText();
               
               Statement stm = conn.createStatement();
               
               String sql =  "select * from login WHERE username = '"+username+"' and password = '"+password+"'";
               ResultSet rs = stm.executeQuery(sql);
               
               if(rs.next()){
                   //dispose();
                    contentScrollPane.setViewportView(new HomePanel(contentScrollPane));
               }else{
                   JOptionPane.showMessageDialog(this,"username or password wrong ...");
                   unameTextField.setText("");
                   passwordTextField.setText("");
               }
               
           }
            
        
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
        System.out.println(e.getMessage());
    }
            
    }//GEN-LAST:event_logBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton logBtn;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JTextField unameTextField;
    // End of variables declaration//GEN-END:variables

}

